baseURL: "https://raphazilla.github.io/raphazilla"
title: "Raphazilla"
theme: PaperMod
languageCode: "pt-br"
defaultContentLanguage: "pt-br"
enableRobotsTXT: true
enableEmoji: true
publishDir: "public"
analytics:
  google:
    SiteVerificationTag: "G-6SVRZ2T5RW"
disqusShortname: "raphazilla"

outputs:
  home:
    - HTML
    - RSS
    - JSON

pagination:
  pagerSize: 6

languages:
  pt-br:
    languageName: "Português (Brasil)"
    weight: 1
    contentDir: "content/pt-br"
    title: "Raphazilla"
    params:
      description: "Explorando tecnologia, automação e insights DevOps."
    menu:
      main:
        - name: Blog
          url: /blog
          weight: 10
        - name: Sobre
          url: /about
          weight: 20
        - name: GitHub
          url: https://github.com/raphazilla
          weight: 30
          params:
            target: "_blank"
        - name: Tags
          url: /tags
          weight: 40
        - name: Archives
          url: /archives
          weight: 50  
        - name: Buscar
          url: /search
          weight: 60
    params:
      homeInfoParams:
        Title: "Raphazilla aqui..😎🖖"
        Content: 👋 E aí, galera? Sou o Rapha, um entusiasta de tecnologia sempre em busca de aprender e compartilhar o que descubro por aí. Aqui é o meu cantinho para trocar ideias sobre as últimas novidades em tecnologia, automação e DevOps. Curto muito inovação e eficiência, e estou sempre aberto a novas descobertas. Bora trocar uma ideia e aprender juntos? 🚀

  en-us:
    languageName: "English"
    weight: 2
    contentDir: "content/en-us"
    title: "Raphazilla"
    params:
      description: "Exploring technology, automation, and DevOps insights."
    menu:
      main:
        - name: Blog
          url:  /blog
          weight: 10
        - name: About
          url: /about
          weight: 20
        - name: GitHub
          url: https://github.com/raphazilla
          weight: 30
          params:
            target: "_blank"
        - name: Tags
          url: /tags
          weight: 40
        - name: Archives
          url: /archives
          weight: 50  
        - name: Search
          url: /search
          weight: 60
    params:
      homeInfoParams:
        Title: "Raphazilla here..😎🖖"
        Content: 👋 Hey folks! I'm Rapha, a tech enthusiast always eager to learn and share what I discover. This is my little corner to chat about the latest in technology, automation, and DevOps. I'm all about innovation and efficiency, and I'm always open to new insights. Want to connect and learn together? 🚀
        alertbar: true 

params:
  env: production
  description: "Another Techblog.."
  author: "Rapha"
  avatar: "images/author.jpg"
  comments: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: true
  defaultTheme: "dark"
  logo: "images/author.webp"
  defaultCover:
    image: "images/hero-banner.jpg"
    alt: "Imagem padrão"
  editPost:
    URL: "https://github.com/raphazilla/raphazilla/content"
    appendFilePath: true
  
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

  socialIcons:
    - name: github
      title: "GitHub"
      url: "https://github.com/raphazilla"
    - name: linkedin
      title: "LinkedIn"
      url: "https://linkedin.com/in/raphaelprosillo"
    - name: twitter
      title: "Twitter"
      url: "https://twitter.com/ollisorp"

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: github
    anchorLineNos: true
    anchorLineNosStyle: github

server:
  watch: true
  disableFastRender: true
